const root=document.documentElement;
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.addEventListener('pointermove',e=>{root.style.setProperty('--x',`${e.clientX}px`);root.style.setProperty('--y',`${e.clientY}px`);document.querySelectorAll('.glass,.glass-section,.glass-photo').forEach(el=>{const r=el.getBoundingClientRect();el.style.setProperty('--lx',`${e.clientX-r.left}px`);el.style.setProperty('--ly',`${e.clientY-r.top}px`)})});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:reduce?'auto':'smooth'})}}));
const lb=document.getElementById('lightbox'),lbi=lb.querySelector('img');document.querySelectorAll('[data-full]').forEach(b=>b.addEventListener('click',()=>{lbi.src=b.dataset.full;lb.classList.add('open');lb.setAttribute('aria-hidden','false')}));function closeLB(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true');lbi.src=''}lb.querySelector('.lightbox-close').addEventListener('click',closeLB);lb.addEventListener('click',e=>{if(e.target===lb)closeLB()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLB()});
if(!reduce){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.18,y=(e.clientY-r.top-r.height/2)*.18;el.style.transform=`translate(${x}px,${y}px) scale(1.08)`});el.addEventListener('pointerleave',()=>el.style.transform='')});const tilt=document.querySelector('.tilt');tilt?.addEventListener('pointermove',e=>{const r=tilt.getBoundingClientRect(),rx=((e.clientY-r.top)/r.height-.5)*-4,ry=((e.clientX-r.left)/r.width-.5)*4;tilt.style.transform=`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg)`});tilt?.addEventListener('pointerleave',()=>tilt.style.transform='')}
const items=[...document.querySelectorAll('.timeline-item')],bar=document.querySelector('.timeline-progress i'),topBtn=document.querySelector('.to-top');function onScroll(){const y=innerHeight*.52;let active=0;items.forEach((it,i)=>{const r=it.getBoundingClientRect();if(r.top<y)active=i;it.classList.toggle('active',r.top<y&&r.bottom>innerHeight*.2)});if(bar)root.style.setProperty('--timeline',items.length>1?`${active/(items.length-1)*100}%`:'0%');topBtn.classList.toggle('show',scrollY>innerHeight*1.1);if(!reduce){document.querySelectorAll('.parallax-photo').forEach(p=>{const r=p.getBoundingClientRect(),v=Math.max(-10,Math.min(10,(innerHeight/2-(r.top+r.height/2))*.025));p.style.setProperty('--py',`${v}px`)})}}addEventListener('scroll',onScroll,{passive:true});onScroll();

// v07 — active section in the glass navigation
const navLinks=[...document.querySelectorAll('.topbar a[href^="#"]')];
const navSections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);
const navObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`));}})},{rootMargin:'-32% 0px -52% 0px',threshold:0});
navSections.forEach(s=>navObserver.observe(s));

// v08 gallery controls
(()=>{const g=document.getElementById('lifeGallery'); if(!g)return; const wrap=g.closest('.gallery-wrap'); const step=()=>Math.max(240,Math.min(g.clientWidth*.72,380)); wrap.querySelector('.gallery-prev').addEventListener('click',()=>g.scrollBy({left:-step(),behavior:'smooth'})); wrap.querySelector('.gallery-next').addEventListener('click',()=>g.scrollBy({left:step(),behavior:'smooth'}));})();
